version: "3.9"

services:
  app:
    build: .
    container_name: my_players
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    command: bash -c "yarn && node database.js && npm run start"
